begin;
create extension if not exists pgtap with schema extensions;
select plan(12);
select ok((select relrowsecurity from pg_class where oid='private.privacy_request_operators'::regclass),'operators RLS enabled');
select ok((select relrowsecurity from pg_class where oid='private.privacy_request_events'::regclass),'history RLS enabled');
select ok(not has_table_privilege('authenticated','private.privacy_request_operators','SELECT,INSERT,UPDATE,DELETE'),'authenticated has no operator privileges');
select ok(not has_table_privilege('authenticated','private.privacy_request_events','SELECT,INSERT,UPDATE,DELETE'),'authenticated has no history privileges');
select ok(not has_table_privilege('anon','private.privacy_request_operators','SELECT,INSERT,UPDATE,DELETE'),'anonymous has no operator privileges');
select ok(not has_table_privilege('anon','private.privacy_request_events','SELECT,INSERT,UPDATE,DELETE'),'anonymous has no history privileges');
select ok(not has_table_privilege('service_role','private.privacy_request_operators','SELECT,INSERT,UPDATE,DELETE'),'service role has no operator grants');
select ok(not has_table_privilege('service_role','private.privacy_request_events','SELECT,INSERT,UPDATE,DELETE'),'service role has no history grants');
select ok(not has_column_privilege('authenticated','public.privacy_requests','revision','INSERT'),'requester cannot forge revision');
select ok(not has_table_privilege('authenticated','public.privacy_requests','UPDATE'),'requester cannot mutate status');
set local role authenticated;
select throws_ok($$select * from private.privacy_request_events$$,'42501',null,'history is denied at SQL boundary');
select throws_ok($$select * from private.privacy_request_operators$$,'42501',null,'operator mapping is denied at SQL boundary');
reset role;
select * from finish();
rollback;
