create type public.recommendation_portfolio_status as enum('draft','validated','published','archived');
create type public.recommendation_priority_level as enum('critical','high','medium','low','future');
create type public.recommendation_portfolio_category as enum('quick_wins','strategic_projects','high_roi','low_investment','ai_first','automation_first','operational_excellence','compliance','risk_reduction','long_term');
create type public.recommendation_roadmap_phase as enum('phase_1','phase_2','phase_3','phase_4');
create type public.recommendation_validation_severity as enum('error','warning','information');
create table public.recommendation_rule_catalog(id uuid primary key default gen_random_uuid(),organization_id uuid references public.organizations(id),code text not null,version integer not null check(version>0),title text not null,description text not null,priority_formula jsonb not null,match_json jsonb not null,dependencies jsonb not null default '[]' check(jsonb_typeof(dependencies)='array'),category public.recommendation_portfolio_category not null,published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique nulls not distinct(code,version,organization_id));
create table public.priority_definition_catalog(id uuid primary key default gen_random_uuid(),organization_id uuid references public.organizations(id),code text not null,version integer not null check(version>0),title text not null,formula_json jsonb not null,thresholds_json jsonb not null,published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique nulls not distinct(code,version,organization_id));
create table public.recommendation_portfolio_snapshots(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,company_id uuid not null,roi_snapshot_id uuid not null,automation_opportunity_snapshot_id uuid not null,ai_opportunity_snapshot_id uuid not null,business_analysis_id uuid not null,process_map_id uuid not null,knowledge_snapshot_id uuid not null,previous_version_id uuid references public.recommendation_portfolio_snapshots(id),version_number integer not null,status public.recommendation_portfolio_status not null default'draft',lock_version integer not null default 1,catalog_versions_json jsonb not null,provenance_json jsonb not null,created_by uuid not null,validated_at timestamptz,published_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(id,organization_id),unique(organization_id,roi_snapshot_id,version_number),foreign key(company_id,organization_id)references public.companies(id,organization_id),foreign key(roi_snapshot_id,organization_id)references public.roi_evaluation_snapshots(id,organization_id));
create table public.transformation_recommendations(id uuid primary key default gen_random_uuid(),organization_id uuid not null,snapshot_id uuid not null,rule_id uuid not null references public.recommendation_rule_catalog(id),priority_definition_id uuid not null references public.priority_definition_catalog(id),roi_evaluation_id uuid not null,roi_scenario_id uuid not null,roi_snapshot_id uuid not null,automation_opportunity_id uuid not null,automation_opportunity_snapshot_id uuid not null,identifier text not null,title text not null,description text not null,business_problem text not null,recommended_initiative text not null,expected_benefits jsonb not null,implementation_cost numeric(18,4) not null,expected_roi numeric(18,4),roi_special_value text,payback numeric(18,4),business_impact numeric(5,2) not null,complexity numeric(5,2) not null,feasibility numeric(5,2) not null,operational_risk numeric(5,2) not null,confidence numeric(5,2) not null,priority_score numeric(5,2) not null,priority public.recommendation_priority_level not null,category public.recommendation_portfolio_category not null,roadmap_phase public.recommendation_roadmap_phase not null,prerequisites_json jsonb not null default'[]',affected_process_ids uuid[] not null default'{}',affected_department_ids uuid[] not null default'{}',affected_system_ids uuid[] not null default'{}',created_at timestamptz not null default now(),unique(snapshot_id,identifier),unique(id,snapshot_id,organization_id),foreign key(snapshot_id,organization_id)references public.recommendation_portfolio_snapshots(id,organization_id)on delete cascade,foreign key(roi_evaluation_id,roi_scenario_id,roi_snapshot_id,organization_id)references public.roi_evaluations(id,scenario_id,snapshot_id,organization_id),foreign key(automation_opportunity_id,automation_opportunity_snapshot_id,organization_id)references public.automation_opportunities(id,snapshot_id,organization_id));
create table public.transformation_recommendation_dependencies(recommendation_id uuid not null,depends_on_id uuid not null,snapshot_id uuid not null,organization_id uuid not null,reason text not null,created_at timestamptz not null default now(),primary key(recommendation_id,depends_on_id),foreign key(recommendation_id,snapshot_id,organization_id)references public.transformation_recommendations(id,snapshot_id,organization_id)on delete cascade,foreign key(depends_on_id,snapshot_id,organization_id)references public.transformation_recommendations(id,snapshot_id,organization_id));
create table public.transformation_recommendation_evidence(id uuid primary key default gen_random_uuid(),recommendation_id uuid not null,snapshot_id uuid not null,organization_id uuid not null,roi_evidence_id uuid not null references public.roi_evidence(id),business_finding_id uuid not null references public.business_findings(id),knowledge_fact_id uuid not null references public.knowledge_facts(id),explanation text not null,created_at timestamptz not null default now(),unique(recommendation_id,roi_evidence_id),foreign key(recommendation_id,snapshot_id,organization_id)references public.transformation_recommendations(id,snapshot_id,organization_id)on delete cascade);
create table public.transformation_recommendation_contributions(id uuid primary key default gen_random_uuid(),recommendation_id uuid not null,snapshot_id uuid not null,organization_id uuid not null,component text not null,raw_value numeric(18,4) not null,normalized_value numeric(5,2) not null,weight numeric(8,4) not null,weighted_contribution numeric(8,4) not null,calculation_json jsonb not null,created_at timestamptz not null default now(),unique(recommendation_id,component),foreign key(recommendation_id,snapshot_id,organization_id)references public.transformation_recommendations(id,snapshot_id,organization_id)on delete cascade);
create table public.recommendation_portfolio_validations(id uuid primary key default gen_random_uuid(),organization_id uuid not null,snapshot_id uuid not null,code text not null,severity public.recommendation_validation_severity not null,message text not null,created_at timestamptz not null default now(),foreign key(snapshot_id,organization_id)references public.recommendation_portfolio_snapshots(id,organization_id)on delete cascade);
do $$declare t text;begin foreach t in array array['recommendation_rule_catalog','priority_definition_catalog','recommendation_portfolio_snapshots']loop execute format('create trigger %I_updated_at before update on public.%I for each row execute function private.set_updated_at()',t,t);end loop;end$$;
create function private.validate_recommendation_source()returns trigger language plpgsql set search_path=''as $$begin if not exists(select 1 from public.roi_evaluation_snapshots r join public.automation_opportunity_snapshots au on au.id=r.automation_opportunity_snapshot_id and au.organization_id=r.organization_id join public.ai_opportunity_snapshots ai on ai.id=r.ai_opportunity_snapshot_id and ai.organization_id=r.organization_id join public.analysis_snapshots a on a.id=r.business_analysis_id and a.organization_id=r.organization_id join public.process_maps p on p.id=r.process_map_id and p.organization_id=r.organization_id join public.knowledge_snapshots k on k.id=r.knowledge_snapshot_id and k.organization_id=r.organization_id where r.id=new.roi_snapshot_id and r.organization_id=new.organization_id and r.company_id=new.company_id and r.status='published'and au.id=new.automation_opportunity_snapshot_id and au.status='published'and ai.id=new.ai_opportunity_snapshot_id and ai.status='published'and a.id=new.business_analysis_id and a.status='published'and p.id=new.process_map_id and p.status='published'and r.knowledge_snapshot_id=new.knowledge_snapshot_id and k.status='ready')then raise exception'Recommendation requires aligned published canonical sources';end if;return new;end$$;
revoke execute on function private.validate_recommendation_source()from public,anon,authenticated;create trigger recommendation_source_valid before insert on public.recommendation_portfolio_snapshots for each row execute function private.validate_recommendation_source();
create function private.prevent_frozen_recommendation_catalog_mutation()returns trigger language plpgsql set search_path=''as $$declare k text;begin if old.published then raise exception'Published Recommendation catalog versions are immutable';end if;k:=case tg_table_name when'recommendation_rule_catalog'then'rules'else'priorityDefinitions'end;if exists(select 1 from public.recommendation_portfolio_snapshots s where s.catalog_versions_json@>jsonb_build_object(k,jsonb_build_array(jsonb_build_object('id',old.id::text))))then raise exception'Recommendation catalog version is frozen';end if;if tg_op='DELETE'then return old;else return new;end if;end$$;
revoke execute on function private.prevent_frozen_recommendation_catalog_mutation()from public,anon,authenticated;create trigger recommendation_rules_immutable before update or delete on public.recommendation_rule_catalog for each row execute function private.prevent_frozen_recommendation_catalog_mutation();create trigger priority_definitions_immutable before update or delete on public.priority_definition_catalog for each row execute function private.prevent_frozen_recommendation_catalog_mutation();
create function private.prevent_published_recommendation_mutation()returns trigger language plpgsql security definer set search_path=''as $$declare sid uuid;begin if tg_table_name='recommendation_portfolio_snapshots'then if old.status='published'then raise exception'Published Recommendation snapshots are immutable';end if;if tg_op='DELETE'then return old;else return new;end if;end if;if tg_op='DELETE'then sid:=old.snapshot_id;else sid:=new.snapshot_id;end if;if exists(select 1 from public.recommendation_portfolio_snapshots where id=sid and status='published')then raise exception'Published Recommendation snapshots are immutable';end if;if tg_op='DELETE'then return old;else return new;end if;end$$;
revoke execute on function private.prevent_published_recommendation_mutation()from public,anon,authenticated;create trigger recommendation_snapshots_immutable before update or delete on public.recommendation_portfolio_snapshots for each row execute function private.prevent_published_recommendation_mutation();
do $$declare t text;begin foreach t in array array['transformation_recommendations','transformation_recommendation_dependencies','transformation_recommendation_evidence','transformation_recommendation_contributions','recommendation_portfolio_validations']loop execute format('create trigger %I_immutable before insert or update or delete on public.%I for each row execute function private.prevent_published_recommendation_mutation()',t,t);end loop;end$$;
do $$declare t text;begin foreach t in array array['recommendation_rule_catalog','priority_definition_catalog','recommendation_portfolio_snapshots','transformation_recommendations','transformation_recommendation_dependencies','transformation_recommendation_evidence','transformation_recommendation_contributions','recommendation_portfolio_validations']loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
do $$declare t text;begin foreach t in array array['recommendation_rule_catalog','priority_definition_catalog']loop execute format('create policy "members read %1$s" on public.%1$I for select to authenticated using(%1$I.organization_id is null or(select private.has_organization_role(%1$I.organization_id,array[''owner'',''admin'',''consultant'',''viewer'']::public.organization_role[])))',t);execute format('create policy "admins manage %1$s" on public.%1$I for all to authenticated using(%1$I.organization_id is not null and(select private.has_organization_role(%1$I.organization_id,array[''owner'',''admin'']::public.organization_role[])))with check(%1$I.organization_id is not null and(select private.has_organization_role(%1$I.organization_id,array[''owner'',''admin'']::public.organization_role[])))',t);end loop;end$$;
do $$declare t text;begin foreach t in array array['transformation_recommendations','transformation_recommendation_dependencies','transformation_recommendation_evidence','transformation_recommendation_contributions','recommendation_portfolio_validations']loop execute format('create policy "members read %1$s" on public.%1$I for select to authenticated using((select private.has_organization_role(%1$I.organization_id,array[''owner'',''admin'',''consultant'',''viewer'']::public.organization_role[])))',t);execute format('create policy "editors manage %1$s" on public.%1$I for all to authenticated using((select private.has_organization_role(%1$I.organization_id,array[''owner'',''admin'',''consultant'']::public.organization_role[])))with check((select private.has_organization_role(%1$I.organization_id,array[''owner'',''admin'',''consultant'']::public.organization_role[])))',t);end loop;end$$;
create policy"members read recommendation snapshots"on public.recommendation_portfolio_snapshots for select to authenticated using((select private.has_organization_role(recommendation_portfolio_snapshots.organization_id,array['owner','admin','consultant','viewer']::public.organization_role[])));create policy"editors create recommendation snapshots"on public.recommendation_portfolio_snapshots for insert to authenticated with check((select private.has_organization_role(recommendation_portfolio_snapshots.organization_id,array['owner','admin','consultant']::public.organization_role[])));create policy"editors update recommendation snapshots"on public.recommendation_portfolio_snapshots for update to authenticated using((select private.has_organization_role(recommendation_portfolio_snapshots.organization_id,array['owner','admin','consultant']::public.organization_role[])))with check((select private.has_organization_role(recommendation_portfolio_snapshots.organization_id,array['owner','admin','consultant']::public.organization_role[]))and(recommendation_portfolio_snapshots.status<>'published'or(select private.has_organization_role(recommendation_portfolio_snapshots.organization_id,array['owner','admin']::public.organization_role[]))));
grant select,insert,update,delete on public.recommendation_rule_catalog,public.priority_definition_catalog,public.recommendation_portfolio_snapshots,public.transformation_recommendations,public.transformation_recommendation_dependencies,public.transformation_recommendation_evidence,public.transformation_recommendation_contributions,public.recommendation_portfolio_validations to authenticated;
insert into public.priority_definition_catalog(code,version,title,formula_json,thresholds_json,published)values('portfolio_priority',1,'Portfolio Priority','{"roi":0.30,"business_impact":0.25,"feasibility":0.15,"inverse_complexity":0.10,"operational_risk":0.10,"confidence":0.10}','{"critical":85,"high":70,"medium":50,"low":30,"future":0}',true);
insert into public.recommendation_rule_catalog(code,version,title,description,priority_formula,match_json,dependencies,category,published)values
('quick_win',1,'Quick Win','High-return low-complexity initiative','{"definition":"portfolio_priority"}','{"precedence":1,"initiative":"Implement the automation opportunity","benefit":"Capture near-term value"}','[]','quick_wins',true),
('compliance',1,'Compliance Initiative','Address compliance findings','{"definition":"portfolio_priority"}','{"precedence":2,"initiative":"Implement controlled compliance improvements","benefit":"Reduce compliance exposure"}','[]','compliance',true),
('risk_reduction',1,'Risk Reduction','Reduce material operational risk','{"definition":"portfolio_priority"}','{"precedence":3,"initiative":"Implement risk controls","benefit":"Reduce operational exposure"}','[]','risk_reduction',true),
('ai_first',1,'AI First','AI-enabled initiative','{"definition":"portfolio_priority"}','{"precedence":4,"initiative":"Implement the governed AI-enabled initiative","benefit":"Capture governed AI value"}','[]','ai_first',true),
('automation_first',1,'Automation First','Deterministic automation initiative','{"definition":"portfolio_priority"}','{"precedence":5,"initiative":"Implement the deterministic automation","benefit":"Reduce manual work"}','[]','automation_first',true),
('strategic_project',1,'Strategic Project','High-impact complex initiative','{"definition":"portfolio_priority"}','{"precedence":6,"initiative":"Plan and execute the strategic initiative","benefit":"Deliver structural improvement"}','[]','strategic_projects',true),
('high_roi',1,'High ROI','High-return initiative','{"definition":"portfolio_priority"}','{"precedence":7,"initiative":"Implement the high-return initiative","benefit":"Capture strong economic value"}','[]','high_roi',true),
('low_investment',1,'Low Investment','Below-median investment initiative','{"definition":"portfolio_priority"}','{"precedence":8,"initiative":"Implement the low-investment initiative","benefit":"Capture value with limited capital"}','[]','low_investment',true),
('operational_excellence',1,'Operational Excellence','High-readiness improvement','{"definition":"portfolio_priority"}','{"precedence":9,"initiative":"Implement the operational improvement","benefit":"Improve execution quality"}','[]','operational_excellence',true),
('long_term',1,'Long Term','Long-term transformation initiative','{"definition":"portfolio_priority"}','{"precedence":10,"initiative":"Prepare the long-term initiative","benefit":"Build future capability"}','[]','long_term',true);
